# Model arguments
model_name_or_path: /group/40101/milkcychen/SEED-Bench-R1/pretrained_ckpt/Qwen2-VL-7B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: xxx
jsonl_path: /group/40101/milkcychen/SEED-Bench-R1/data/annotations/training_with_cot_6k.jsonl
data_root_dir: /group/40101/milkcychen/SEED-Bench-R1/data

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: "no"
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 8192
max_steps: -1
num_train_epochs: 1
output_dir: /group/40101/milkcychen/SEED-Bench-R1/ckpt/Qwen2-VL-7B-Instruct-SFT/training_with_cot_6k
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
report_to:
- wandb
save_strategy: steps
seed: 42
warmup_ratio: 0.1
save_steps: 1
save_only_model: true